name: Deploy via FTP

on:
  push:
    branches: ["main"]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'Steve-CPlus/tidyguy-test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action.3.5@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /duncan/
          exclude: |
            .git*
            .github/workflows/deploy.yml
            README.md
